language: php

# list any PHP version you want to test against
php:
  - '5.6'
  - '7.1'

before_script:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --no-configuration avadim\Qevix\QevixTest test/QevixTest.php
