language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script: phpunit --bootstrap test/bootstrap.php --no-configuration avadim\Qevix\QevixTest test/QevixTest.php
